const grid = document.getElementById("productsGrid");
const emptyMessage = document.getElementById("emptyMessage");
const searchInput = document.getElementById("searchInput");
const filterButtons = document.querySelectorAll(".filter-btn");
const cartPanel = document.getElementById("cartPanel");
const overlay = document.getElementById("overlay");
const cartItems = document.getElementById("cartItems");
const cartTotal = document.getElementById("cartTotal");
const cartTotalTop = document.getElementById("cartTotalTop");
const cartCountTop = document.getElementById("cartCountTop");
const cartSmallInfo = document.getElementById("cartSmallInfo");
const modal = document.getElementById("productModal");
const modalContent = document.getElementById("modalContent");
let currentFilter = "all";
let cart = JSON.parse(localStorage.getItem("exotiako-cart-v2")) || [];
const euro = value => value.toLocaleString("fr-FR", { style: "currency", currency: "EUR" });
function saveCart(){localStorage.setItem("exotiako-cart-v2", JSON.stringify(cart));renderCart();}
function showToast(message){const t=document.createElement("div");t.className="toast";t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),1900)}
function renderProducts(){const query=searchInput.value.trim().toLowerCase();const filtered=PRODUCTS.filter(p=>{const matchFilter=currentFilter==="all"||p.category===currentFilter;const matchQuery=[p.name,p.short,p.description,p.categoryLabel].join(" ").toLowerCase().includes(query);return matchFilter&&matchQuery});grid.innerHTML=filtered.map(productCard).join("");emptyMessage.style.display=filtered.length?"none":"block";}
function productCard(p){const hasVariants=Array.isArray(p.variants);return `<article class="card"><div class="card-image"><img src="${p.image}" alt="${p.name}"></div><div class="card-body"><span class="badge">${p.categoryLabel}</span><h3>${p.name}</h3><p>${p.short}</p><div class="price">Dès ${euro(p.price)} <small>/${p.unit}</small></div>${hasVariants?`<div class="variant-note">Choix : ${p.variants.map(v=>v.name.toLowerCase()).join(", ")}</div>`:""}<div class="actions"><button class="btn ghost" onclick="openDetail('${p.id}')">ⓘ Détail</button><button class="btn primary" onclick="${hasVariants?`openDetail('${p.id}')`:`quickAdd('${p.id}')`}">${hasVariants?"☷ Choisir":"🛒 Ajouter"}</button></div></div></article>`}
function openDetail(id){const p=PRODUCTS.find(x=>x.id===id);let selected=p.variants?.[0]?.id||"";modalContent.innerHTML=`<div class="modal-grid"><img src="${p.image}" alt="${p.name}"><div class="modal-info"><h2>${p.name}</h2><span class="badge">${p.categoryLabel}</span><p>${p.description}</p><div class="price" id="modalPrice">${euro(p.variants?p.variants[0].price:p.price)} <small>/${p.unit}</small></div>${p.variants?`<div class="variant-list">${p.variants.map((v,i)=>`<button class="variant-btn ${i===0?"selected":""}" data-variant="${v.id}" data-price="${v.price}" type="button"><span>${v.name}</span><strong>${euro(v.price)}</strong></button>`).join("")}</div>`:""}<div class="modal-actions"><input id="modalQty" type="number" min="1" value="1"><button class="btn primary" id="modalAdd">Ajouter au panier</button></div></div></div>`;modal.showModal();const buttons=modalContent.querySelectorAll(".variant-btn");buttons.forEach(btn=>btn.addEventListener("click",()=>{buttons.forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");selected=btn.dataset.variant;document.getElementById("modalPrice").innerHTML=`${euro(Number(btn.dataset.price))} <small>/${p.unit}</small>`}));document.getElementById("modalAdd").onclick=()=>{const qty=Math.max(1,Number(document.getElementById("modalQty").value||1));const variant=p.variants?.find(v=>v.id===selected);addToCart(p,qty,variant);modal.close();};}
function quickAdd(id){const p=PRODUCTS.find(x=>x.id===id);addToCart(p,1,null)}
function addToCart(product,quantity,variant){const key=variant?`${product.id}-${variant.id}`:product.id;const name=variant?`${product.name} - ${variant.name}`:product.name;const price=variant?variant.price:product.price;const existing=cart.find(i=>i.key===key);if(existing) existing.quantity+=quantity; else cart.push({key,id:product.id,name,price,unit:product.unit,image:product.image,quantity});saveCart();showToast(`${name} ajouté au panier`);}
function renderCart(){const count=cart.reduce((s,i)=>s+i.quantity,0);const total=cart.reduce((s,i)=>s+i.price*i.quantity,0);cartCountTop.textContent=count;cartTotalTop.textContent=euro(total);cartTotal.textContent=euro(total);cartSmallInfo.textContent=`${count} article${count>1?"s":""}`;cartItems.innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><img src="${i.image}" alt="${i.name}"><div><h4>${i.name}</h4><small>${euro(i.price)} / ${i.unit}</small><div class="qty"><button onclick="changeQty('${i.key}',-1)">−</button><span>${i.quantity}</span><button onclick="changeQty('${i.key}',1)">+</button></div></div><strong>${euro(i.price*i.quantity)}</strong></div>`).join(""):`<p>Votre panier est vide.</p>`;}
function changeQty(key,delta){const item=cart.find(i=>i.key===key);if(!item)return;item.quantity+=delta;if(item.quantity<=0)cart=cart.filter(i=>i.key!==key);saveCart();}
function openCart(){cartPanel.classList.add("open");overlay.classList.add("show");cartPanel.setAttribute("aria-hidden","false")}
function closeCart(){cartPanel.classList.remove("open");overlay.classList.remove("show");cartPanel.setAttribute("aria-hidden","true")}
filterButtons.forEach(btn=>btn.addEventListener("click",()=>{filterButtons.forEach(b=>b.classList.remove("active"));btn.classList.add("active");currentFilter=btn.dataset.filter;renderProducts()}));
searchInput.addEventListener("input",renderProducts);document.getElementById("cartOpenTop").onclick=openCart;document.getElementById("cartOpenNav").onclick=openCart;document.getElementById("cartClose").onclick=closeCart;overlay.onclick=closeCart;document.getElementById("modalClose").onclick=()=>modal.close();document.getElementById("clearCart").onclick=()=>{cart=[];saveCart();};
document.getElementById("mailOrder").onclick=()=>{if(!cart.length){showToast("Votre panier est vide");return}const body=cart.map(i=>`- ${i.name} x${i.quantity} = ${euro(i.price*i.quantity)}`).join("%0D%0A");const total=euro(cart.reduce((s,i)=>s+i.price*i.quantity,0));window.location.href=`mailto:contact@exotiako.mg?subject=Commande ExoTiako&body=Bonjour,%0D%0A%0D%0AJe souhaite commander :%0D%0A${body}%0D%0A%0D%0ATotal : ${total}%0D%0A%0D%0AMes coordonnées :%0D%0ANom :%0D%0ATéléphone :%0D%0AAdresse :`;};
renderProducts();renderCart();
